# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
issues:
  max-same-issues: 0
  exclude-dirs:
    - mocks/

linters:
  disable-all: true
  enable:
    - durationcheck
    - errcheck
    - copyloopvar
    - forcetypeassert
    - godot
    - gofmt
    - gosimple
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused
    - govet
