FROM ubuntu:22.04

SHELL ["/bin/bash", "-c"]

RUN apt update && apt upgrade -y
RUN apt install -y git make musl-dev curl bison

ARG TARGETOS="linux"
ARG TARGETARCH="amd64"

ARG GOLANG_VERSION="1.20.3"

RUN curl -sSL https://go.dev/dl/go${GOLANG_VERSION}.${TARGETOS}-${TARGETARCH}.tar.gz -o golang.tar.gz \
  && tar -C /usr/local -xzf golang.tar.gz \
  && rm -rf golang.tar.gz

ENV GOPATH=/usr/local/go
ENV GO_BIN_PATH=/usr/local/go/bin

ARG NODE_VERSION="18.16.0"

ENV NVM_DIR=/usr/local/nvm

RUN curl -sSL https://raw.githubusercontent.com/creationix/nvm/v0.23.3/install.sh | bash \
    && . ${NVM_DIR}/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default

ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV NODE_BIN_PATH $NVM_DIR/v$NODE_VERSION/bin

ENV PATH $GO_BIN_PATH:$NODE_BIN_PATH:$PATH

RUN curl -sSL https://taskfile.dev/install.sh | bash -s -- -d
RUN go install github.com/cosmtrek/air@latest

ENTRYPOINT [ "/bin/bash" ]
