version: '3'

tasks:
  build:
    summary: "Build the Terralist binary."
    silent: true
    vars:
      ARG:
        sh: echo "{{default "release" .CLI_ARGS}}"
      ARG_CHECKER:
        sh: echo "{{has .ARG (list "debug" "release")}}"
      MODE:
        sh: echo "{{ternary .ARG "release" (eq .ARG_CHECKER "true")}}"
      BRANCH:
        sh: git rev-parse --abbrev-ref HEAD
      COMMIT_HASH:
        sh: git rev-parse --short HEAD
    cmds:
      - >-
        echo "{{
          ternary 
            (printf "[>] Building in '%s' mode." .MODE) 
            (printf "[!] Build mode '%s' unknown, fall-backing to 'release' mode." .CLI_ARGS) 
            (eq .ARG_CHECKER "true")
          }}"
      - >- 
        go build \
          -o={{printf "terralist%s" (ternary ".exe" "" (eq OS "windows"))}} \
          -v \
          -ldflags="-X 'main.Version={{.BRANCH}}' \
                    -X 'main.CommitHash={{.COMMIT_HASH}}' \
                    -X 'main.BuildTimestamp={{now | date "2006-01-02T15:04:05"}}' \
                    -X 'main.Mode=release'" \
          ./cmd/terralist/main.go
